### ISSUE TITLE
Distributed cache is not working

### ISSUE THREAD

**Issue by WillWei1983** [moqui/moqui-hazelcast#2]
Hi 
I am running tow moqui instances in my pc(windows10) with different ports and using the moqui-hazelcast in component, and I use the below setups for the cache in MoquiDevConf.xml

```
<cache name="entity.record.one." max-elements="20000" eviction-strategy="least-frequently-used"
                key-type="org.moqui.entity.EntityCondition" value-type="org.moqui.impl.entity.EntityValueBase" type="distributed"/>
        <cache name="entity.record.list." max-elements="10000" eviction-strategy="least-frequently-used"
                key-type="org.moqui.entity.EntityCondition" value-type="org.moqui.impl.entity.EntityListImpl" type="distributed"/>
        <cache name="entity.record.count." max-elements="10000" eviction-strategy="least-frequently-used"  key-type="org.moqui.entity.EntityCondition" value-type="Long" type="distributed"/>
        <cache name="entity.record.one_ra." max-elements="40000" eviction-strategy="least-frequently-used" key-type="org.moqui.entity.EntityCondition" value-type="Set" type="distributed"/>
        <cache name="entity.record.one_view_ra." max-elements="40000" eviction-strategy="least-frequently-used"  key-type="org.moqui.entity.EntityCondition" value-type="Set" type="distributed"/>
        <cache name="entity.record.one_bf" max-elements="1000" eviction-strategy="least-frequently-used"  value-type="Set" type="distributed"/>
        <cache name="entity.record.list_ra." max-elements="20000" eviction-strategy="least-frequently-used"
                key-type="org.moqui.entity.EntityCondition" value-type="Set" type="distributed"/>
        <cache name="entity.record.list_view_ra." max-elements="20000" eviction-strategy="least-frequently-used"  key-type="org.moqui.entity.EntityCondition" value-type="Set" type="distributed"/>

        <cache name="entity.sequence.bank" value-type="long[]" type="distributed"/>
```

but when create demo example record or orders , the primary id always plus 50.
After debug the code in EntityFacadeImpl.groovy, I can see the cause is that in
protected String dbSequencedIdPrimary(String seqName, long staggerMax, long bankSize) {

long[] bank = (long[]) entitySequenceBankCache.get(seqName)

the values from this cache always bank[0] =0, bank[1]=-1. then the value in moqui.entity.SequenceValueItem will be updated everytimes. but the value in cache didn't get changed
any other special setup is needed that I was missing? like the cluster setups?

**Comment by jonesde** [comment]
Yeah, don't do that. Ever. In fact, in general distributed caches are a bad idea for nearly all of the framework caches. Even the entity caches don't work distributed because the auto cache clearing data, which is also in a cache, gets messed up.

Distributed caches can be great for application level data, but they aren't transactional and there are potentially other concurrency issues.

I'd recommend reading more about what Hazelcast and others do with distributed caches, and especially for something low level and critical in the framework be REALLY careful.
